// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg4979cWHMXiFzwxS1YSHujylgt3ZGsa4',
    appId: '1:605504401363:web:55f067e89f1b131d084926',
    messagingSenderId: '605504401363',
    projectId: 'gro-bak',
    authDomain: 'gro-bak.firebaseapp.com',
    storageBucket: 'gro-bak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU-FAcH5EDo8iwgN6Scd7u6lssnGlRg9Y',
    appId: '1:605504401363:android:517266787dc38298084926',
    messagingSenderId: '605504401363',
    projectId: 'gro-bak',
    storageBucket: 'gro-bak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFM9_Ed-4w1AiMvNmMR7wgxiYxr4E1CNs',
    appId: '1:605504401363:ios:b823e92d3033892e084926',
    messagingSenderId: '605504401363',
    projectId: 'gro-bak',
    storageBucket: 'gro-bak.appspot.com',
    iosBundleId: 'com.example.groBak',
  );
}
